---
- hosts: all
  become: yes
  tasks:
    - name: restart consul
      systemd:
        name: consul
        state: restarted
    - name: restart nomad
      systemd:
        name: nomad
        state: restarted
    - name: wait for consul to come up
      uri:
        url: "http://localhost:8500/v1/catalog/nodes"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
    - name: wait for nomad to come up
      uri:
        url: "http://127.0.0.1:4646/v1/jobs"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
    - name: start countdash nomad job
      command: nomad job run /vagrant/resources/nomad-jobs/countdash.hcl
