Vagrant.configure("2") do |config|
    config.vm.box = "fredrikhgrelland/hashistack"
    config.vm.box_version = "0.2.2"
    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 4096
        vb.cpus = 2
    end

    # copy project directory ~> for building Docker image inside vagrant box for further testing
    config.vm.provision "file", source: "../../", destination: "/home/vagrant"

    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/vagrant/ansible"
        ansible.playbook = "playbook.yml"
    end
end