name: Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  test:
    # Macos includes virtualbox and vagrant.
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Env
        run: set
        
      # Runs make test
      - name: Run make test
        run: |
          VAGRANT_DEBUG_LAUNCHER="1" vagrant box add scotch/box
          export SSL_CERT_FILE=/opt/vagrant/embedded/cacert.pem
          make test
