name: Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  test:
    # Macos includes virtualbox and vagrant.
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Runs make test
      - name: Run make test
        run: make test
